name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.0.3 # Dart SDK version
  flutter: 3.10.3 # Flutter SDK version

dependencies:
  blur: ^3.1.0
  shake: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  dio: ^5.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  generate: true
  assets:
    - assets/images/
    - assets/
  uses-material-design: true
